name: Build FFmpeg
on:
  workflow_dispatch:
    inputs:
      source_url:
        description: 'URL of FFmpeg source to build.'
        required: true
        type: string

jobs:
  build_ffmpeg_macos:
    runs-on: macos-14
    permissions: 
      contents: write
    steps:
      - name: Install dependencies
        run: brew install wget

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Validate input
        id: input-validation
        run: echo "FFMPEG_VERSION=$(./validate_input.sh '${{ inputs.source_url }}') >> "$GITHUB_OUTPUT"

      - name: Download FFmpeg sources
        run: wget -O ffmpeg.tar.gz '${{ inputs.source_url }}'

      - name: Unpack FFmpeg sources
        run: tar -zxvf ffmpeg.tar.gz --strip-components=1

      - name: Configure build
        run: ./configure --disable-gpl --disable-nonfree --enable-shared --disable-programs --disable-doc
      
      - name: Build FFmpeg
        run: make -j$(sysctl -n hw.physicalcpu)

      - name: Extract dynamic libraries
        run: mkdir -p lib && find -LE . -type f -iregex "^\./lib[a-zA-Z/]+\.[0-9.]+dylib$" -exec cp {} lib \;
      
      - name: Change absolute paths dependency paths to relative
        run: ./change_deps.sh

      - name: Pack and compress libs
        run: tar -zcvf ffmpeg_macos_arm.tar.gz lib

      - name: Upload tar
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg_macos_arm.tar.gz
          path: ffmpeg_macos_arm.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: n${{ steps.input-validation.outputs.FFMPEG_VERSION }}
          files: ffmpeg_macos_arm.tar.gz
